from __future__ import annotations

import json
from textwrap import indent

from dagforge.models import DagSpec, TaskSpec


def _literal(value: object) -> str:
    return repr(value)


def _render_task(task_spec: TaskSpec) -> str:
    parameters = {item.key: item.value for item in task_spec.parameters}
    body = f"""@task(
    task_id={_literal(task_spec.task_id)},
    retries={task_spec.retries},
    retry_delay=timedelta(minutes=5),
    execution_timeout=timedelta(minutes={task_spec.timeout_minutes}),
)
def {task_spec.task_id}() -> dict[str, object]:
    {_literal(task_spec.description)}
    context = get_current_context()
    event = {{
        "task_id": {_literal(task_spec.task_id)},
        "kind": {_literal(task_spec.kind.value)},
        "description": {_literal(task_spec.description)},
        "connection_id": {_literal(task_spec.connection_id)},
        "parameters": {json.dumps(parameters, ensure_ascii=False, indent=8)},
        "run_id": context.get("run_id", ""),
        "logical_date": str(context.get("logical_date") or ""),
    }}
    logger.info("DAG Forge step: %s", json.dumps(event, ensure_ascii=False))
    return event

{task_spec.task_id}_result = {task_spec.task_id}()
"""
    return body


def render_airflow_dag(spec: DagSpec) -> str:
    """Render a deterministic, syntax-safe Airflow 3 DAG from a validated specification.

    Generated tasks implement an executable orchestration contract: they emit structured
    metadata and can be replaced by organization-specific adapter callables without changing
    dependencies, retries, schedules, or governance settings.
    """

    header = f'''"""Generated by DAG Forge.

Pipeline: {spec.display_name}
This file targets the stable Apache Airflow 3 ``airflow.sdk`` authoring interface.
Business adapters should replace the structured contract body of individual tasks.
"""

from __future__ import annotations

import json
import logging
from datetime import timedelta

import pendulum
from airflow.sdk import DAG, get_current_context, task

logger = logging.getLogger(__name__)

DEFAULT_ARGS = {{
    "owner": {_literal(spec.owner)},
    "depends_on_past": False,
}}

with DAG(
    dag_id={_literal(spec.dag_id)},
    description={_literal(spec.description)},
    schedule={_literal(spec.schedule)},
    start_date=pendulum.datetime(2025, 1, 1, tz="UTC"),
    catchup={spec.catchup!r},
    is_paused_upon_creation=False,
    max_active_runs={spec.max_active_runs},
    default_args=DEFAULT_ARGS,
    tags={_literal(spec.tags)},
) as dag:
'''

    blocks = []
    for task_spec in spec.tasks:
        blocks.append(indent(_render_task(task_spec).rstrip(), "    "))

    dependencies: list[str] = []
    for task_spec in spec.tasks:
        for upstream_id in task_spec.upstream_ids:
            dependencies.append(f"    {upstream_id}_result >> {task_spec.task_id}_result")

    footer = "\n".join(dependencies) if dependencies else "    # No dependencies"
    return header + "\n\n".join(blocks) + "\n\n" + footer + "\n"
